### PR TITLE
Default config file, env vars to secrets and editorconfig

### PR DESCRIPTION
**Pull request by bmeneg**
This PR solves both issues #2 and #3 at the same time. I know that would be better to split in two different PRs, even because editorconfig changes is completely offtopic from the other two changes, next time I'll try to do it right :).

I don't really know if these are the best approaches to the problems, so anything you guys think could be done in a better way, please let me know!

### CODE REVIEW

**Comment by julianolf** [comment]
Everything looks fine but there's a but. As we've provided an example of configuration file, that is named "example.config.yaml', why not use "config.yaml" as the default config file name instead of "gobot.config"? The file name "config.yaml" is also in the gitignore file IIRC.

**Comment by bmeneg** [comment]
@julianolf yeah, you're right! Let me change this and than open a new PR. Thanks!

**Comment by bmeneg** [comment]
@julianolf it wasn't necessary to close/open a new PR. Take a look now if it's ok :)

**Review by julianolf — APPROVED** [review]
Everything looks great!

**Pull request merged**
